#!/bin/bash
#We all know that cd . doesn't do anything (or more precisely, changes current directory to the current one). But cd .. is useful, it changes directory to the current parent.
#Wouldn't it be nice if you could change directory to parent's parent? Or parent's parent's parent? Well, this hack will do it.

local -ri n=${#*};
if [ $n -eq 0 -o -d "${!n}" -o "${!n}" == "-" ]; then
    builtin cd "$@";
else
    local e="s:\.\.\.:../..:g";
    builtin cd "${@:1:$n-1}" $(sed -e$e -e$e -e$e <<< "${!n}");
fi
